# Generated by Django 4.1 on 2022-08-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
