# Generated by Django 4.1 on 2022-08-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_menu_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='menu',
        ),
        migrations.DeleteModel(
            name='ProductMenu',
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen.menu'),
            preserve_default=False,
        ),
    ]
