# Generated by Django 4.1 on 2022-08-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributionunit',
            old_name='unit',
            new_name='unit_type',
        ),
        migrations.AddField(
            model_name='distributionunit',
            name='lunch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionunit',
            name='meal_1',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionunit',
            name='meal_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distributionunit',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
