# Generated by Django 4.1 on 2022-08-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_rename_unit_distributionunit_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
