# Generated by Django 4.1 on 2022-08-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_alter_menu_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionunit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['menu']},
        ),
    ]
